# Kubernetes The Terraform Way
:toc:


## Inspiration

After running through the excellent https://github.com/kelseyhightower/kubernetes-the-hard-way[Kubernetes The Hard Way] tutorial,
I wanted to take a crack at turning it all into terraform modules for various cloud providers. This repository is the result
of that effort. It is not meant to be an 'easy button' or a reusable terraform module for anything production, only as a complement
to k-t-h-w to show the relationship between the various `gcloud` resource management commands and the associated terraform resources.

### Provisioning

This module makes heavy use of https://www.terraform.io/docs/provisioners/index.html[Terraform Provisioners], especially the
https://www.terraform.io/docs/provisioners/null_resource.html[Null Resource] provisioner. This is by no means best-practice, in fact
it is frowned upon in terraform use in-general. However, it does show the power of provisioners (and their fragility), more on that later.

## Prerequisites

This module requires all of the prerequisites of k-t-h-w, as well as a working terraform binary. The version used to create this module
is terraform-0.13.0 beta.

## Usage

As this module is a supplement to k-t-h-w, you should start with https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-prerequisites.md[Lab 1]
and continue until you get to https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-prerequisites.md[Lab 3]. This module
creates all resources and provisions all instances (controller and worker instances) that are described in labs 3-11. Once you hit Lab 3, move on to 
Configuring Terraform

### Configuring Terraform

We'll stick with GCP for now (AWS and Azure planned for future inclusion). First you must get credentials for terraform to manage GCP resources.

* Create credentials .json
+
[source]
----
mkdir -p ~/.gcp
gcloud iam service-accounts keys create ~/.gcp/k-t-h-w-account.json --iam-account <your_account_identifier>
----
+
IMPORTANT: The <your_account_identifier> can be found in the 'IAM' tab of your project. It's the Compute Engine default service account entry
+
* Edit `gcp/vars.auto.tfvars` - Enter the full path to the json file created above credential_path, and change the project name to be your project's name.
* Validate setup
+
[source]
----
cd gcp
terraform init
terraform plan
----

### Run Labs 3-11!

If all goes well, you are free to `terraform apply` and watch all the magic happen. When complete, you may continue with k-t-h-w
https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/12-dns-addon.md[Lab 12]

### Tearing down

The beauty of terraform lies in its stateful ability to manage resources. To tear the whole cluster down, simply run `terraform destroy && rm ssl/* kube_configs/*`.
This will destroy all the resources and remove the generated local config files, so it can all be created from scratch again! This saved me a ton of
time and $$ by being able to create / test / destroy in many iterations.

## What about learning?

Though the `terraform apply` above takes care of all the resource creation and provisioning, it is not meant to obscure these steps for ease, rather
to show how terraform's GCP resources work. Here's how all the scripts and terraform files line up with the labs

### Lab 3 - Resource Creation

In Lab 3, the basic network and compute resources are created which will host the kubernetes cluster.

#### Networking

Starting with https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-compute-resources.md#virtual-private-cloud-network[Virtual Private Cloud],
this is created in `gcp/network.tf`. Open this file and check it out. It created the network and subnetwork used by the kubenetes cluster.

#### Firewall

The firewall described in https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-compute-resources.md#firewall-rules[Lab 3 Firewall]
is created in `gcp/firewall.tf`. Take a look at the resources which coincide with the `gcloud` commands used in Lab 3.

#### IP Address

The https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-compute-resources.md#kubernetes-public-ip-address[Address] is created in
`gcp/address.tf`. This is the public address and face of the kubernetes cluster.

#### Compute Instances

There are two sets of compute instances, the controllers and the workers. The counts of controllers and workers can be controlled by setting the
`worker_count` and `controller_count` variables (in `gcp/vars.auto.tfvars`). If they are not set, they default to 3 controllers and 3 workers, as k-t-h-w
does in the labs. These resources are created with the `gcp/instances.tf`.

NOTE: `gcp/instances.tf` has verbose descriptions of the https://www.terraform.io/docs/providers/google/r/compute_instance.html[`google_compute_instance`] resources. Many of the attributes are set to their default value and could be excluded.

### Lab 4 - The SSL

Most of the work for creating SSL / PKI infra is described in `gcp/ssl-provisioner.tf`, leveraging the scripts in `ssl_scripts/`. This provisioner
makes abusive/offensive use of the terraform local-exec provisioner to execute scripts which create the ssl artifacts in `gcp/ssl/*`. The provisioners 
for the workers and controllers will copy these artifacts onto the instances later.

IMPORTANT: Ensure `gcp/ssl/` is empty before running `terraform apply`, in the case where the infrastructure is created and destroyed, the artifacts in this directory will get tainted by the next provisioner and kubernetes will fail bootstrapping.

NOTE: The https://www.terraform.io/docs/providers/google/r/compute_instance.html[Kubelet Client Certificates] are created in `gcp/worker-provisioner.tf`, utitlizing `ssl_scripts/worker.sh` for each worker

### Lab 5 - kubeconfig files

The kubeconfig files used in the labs are created by `gcp/kubeconfig-provisioner.tf` and saved to `gcp/kube_configs` upon creation.

### Lab 6 - Data Encryption

`gcp/ssl/encryption.yaml` is created from `gcp/ssl-provisioner`.

### Lab 7 - Bootstrapping etcd

etcd is bootstrapped via the `gcp/controller-provisioner.tf`, using the `kube_scripts/controller_bootstrap.sh` script.

### Lab 8 - Bootstraping Kubernetes Control Plane

The https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md[Kubernetes Control Plane] is
bootstrapped in `gcp/controller-provisioner.tf` as well, as part of the same `kube_scripts/controller_bootstrap.sh` script that etcd bootstraps with. This
also creates the load balancer, health check, and an nginx redirect to make the health check work.

### Lab 9 - Bootstrap the Workers

The https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md[Worker Bootstrap] happens
in `gcp/worker-provisioner.tf`, using `kube_scripts/worker_bootstrap.sh`. This does all the needful to get the workers up and running and communicating
with the control plane

### Lab 10 - Configuring kubectl

The https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/10-configuring-kubectl.md[kubectl configuration] happens in 
`gcp/kubectl-provisioner.tf`, using `kube_scripts/kubectl-config.sh`. This allows your local machine to use `kubectl` to control the cluster.

### Lab 11 - Pod Routing

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md[Pod Routing] happens in `gcp/routes.tf`. This enables
pods to communicate with other pods.

## Labs 12-14

Labs https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/12-dns-addon.md[12] and https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/13-smoke-test.md[13] should be followed there. When you get to Lab 14, simply run `terraform destroy` in th `gcp` directory, and it takes
care of all resource destruction.


